version: '3.8'

services:
  db:
    image: postgres:15
    container_name: beat_db
    environment:
      POSTGRES_USER: mela
      POSTGRES_PASSWORD: mela
      POSTGRES_DB: beat_platform
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: